# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit_log',
            old_name='performec_by',
            new_name='performed_by',
        ),
        migrations.AddField(
            model_name='server_change_log',
            name='node_changed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Server'),
        ),
        migrations.AddField(
            model_name='software_log',
            name='change_type',
            field=models.CharField(choices=[('AA', 'Add access'), ('RA', 'Remove access')], default='AA', max_length=2),
        ),
        migrations.AddField(
            model_name='software_log',
            name='software_changed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Software'),
        ),
        migrations.AlterField(
            model_name='envtsubtype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dc_prj_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='node',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='sn_ticket',
            name='ticket_id',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='software_license_type',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
