# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0002_auto_20170912_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access_log',
            options={'verbose_name': 'Access Log', 'verbose_name_plural': 'Access Logs'},
        ),
        migrations.AlterModelOptions(
            name='audit_log',
            options={'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='data_log',
            options={'verbose_name': 'Data Log', 'verbose_name_plural': 'Data Logs'},
        ),
        migrations.AlterModelOptions(
            name='dc_administrator',
            options={'verbose_name': 'Data Core Administrator', 'verbose_name_plural': 'Data Core Administrators'},
        ),
        migrations.AlterModelOptions(
            name='dc_user',
            options={'verbose_name': 'Data Core User', 'verbose_name_plural': 'Data Core Users'},
        ),
        migrations.AlterModelOptions(
            name='external_access_log',
            options={'verbose_name': 'External Access Log', 'verbose_name_plural': 'External Access Logs'},
        ),
        migrations.AlterModelOptions(
            name='governance_doc',
            options={'verbose_name': 'Governance Document', 'verbose_name_plural': 'Governance Documents'},
        ),
        migrations.AlterModelOptions(
            name='server_change_log',
            options={'verbose_name': 'Server Change Log', 'verbose_name_plural': 'Server Change Logs'},
        ),
        migrations.AlterModelOptions(
            name='sn_ticket',
            options={'verbose_name': 'SN Ticket', 'verbose_name_plural': 'SN Tickets'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AlterModelOptions(
            name='software_license_type',
            options={'verbose_name': 'Software License Type', 'verbose_name_plural': 'Software License Types'},
        ),
        migrations.AlterModelOptions(
            name='software_log',
            options={'verbose_name': 'Software Log', 'verbose_name_plural': 'Software Logs'},
        ),
        migrations.AlterModelOptions(
            name='software_purchase',
            options={'verbose_name': 'Software Purchase', 'verbose_name_plural': 'Software Purchases'},
        ),
        migrations.AlterModelOptions(
            name='storage_log',
            options={'verbose_name': 'Storage Log', 'verbose_name_plural': 'Storage Logs'},
        ),
        migrations.AlterField(
            model_name='access_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='audit_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='data_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='dc_administrator',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dc_administrator',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='dc_user',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='external_access_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='governance_doc',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='server_change_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='software',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='software_license_type',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='software_purchase',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='storage_log',
            name='sn_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SN_Ticket'),
        ),
    ]
