# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0004_auto_20170913_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Server'),
        ),
        migrations.AlterField(
            model_name='governance_doc',
            name='users_permitted',
            field=models.ManyToManyField(blank=True, to='dc_management.DC_User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sn_tickets',
            field=models.ManyToManyField(blank=True, to='dc_management.SN_Ticket'),
        ),
        migrations.AlterField(
            model_name='project',
            name='software_installed',
            field=models.ManyToManyField(blank=True, db_table='prj_soft_install_tbl', related_name='software_installed', to='dc_management.Software'),
        ),
        migrations.AlterField(
            model_name='project',
            name='software_requested',
            field=models.ManyToManyField(blank=True, db_table='prj_soft_request_tbl', related_name='software_requested', to='dc_management.Software'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, to='dc_management.DC_User'),
        ),
    ]
