# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0005_auto_20170913_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_user',
            name='cwid',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
