# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0008_auto_20171011_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governance_doc',
            name='defers_to_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Governance_Doc'),
        ),
    ]
