# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0009_auto_20171011_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='audit_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='data_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dc_administrator',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dc_user',
            name='role',
            field=models.CharField(choices=[('FC', 'Faculty'), ('SN', 'Statistician'), ('AF', 'Affiliate'), ('RC', 'Research Coordinator'), ('SF', 'Staff'), ('ST', 'Student'), ('VO', 'Volunteer'), ('OT', 'Other'), ('EX', 'Role Expired')], default='FC', max_length=2),
        ),
        migrations.AlterField(
            model_name='dc_user',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='external_access_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='governance_doc',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='postdata_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='predata_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='sn_tickets',
        ),
        migrations.AddField(
            model_name='project',
            name='sn_tickets',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server_change_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='software_license_type',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='software_purchase',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='softwarepurchase',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='storage_log',
            name='sn_ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
