# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0011_auto_20171013_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='governance_doc',
            name='supersedes_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superseded_by', to='dc_management.Governance_Doc'),
        ),
        migrations.AlterField(
            model_name='governance_doc',
            name='defers_to_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrules', to='dc_management.Governance_Doc'),
        ),
    ]
