# Generated by Django 2.0 on 2017-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0017_auto_20171220_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fileshare_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nickname',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
