# Generated by Django 2.0 on 2018-01-04 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0018_auto_20171221_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.Software')),
            ],
        ),
        migrations.CreateModel(
            name='UserCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('user_quantity', models.IntegerField()),
                ('user_cost', models.FloatField()),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='softwarepurchase',
            name='sw_purchased',
        ),
        migrations.RemoveField(
            model_name='softwarepurchase',
            name='unit',
        ),
        migrations.RenameField(
            model_name='software_purchase',
            old_name='num_licenses_purchased',
            new_name='num_units_purchased',
        ),
        migrations.AddField(
            model_name='software_purchase',
            name='invoice_number',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_purchase',
            name='unit_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dc_management.SoftwareUnit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='function',
            field=models.CharField(choices=[('PR', 'Production'), ('TE', 'Test'), ('DE', 'Development')], default='PR', max_length=2),
        ),
        migrations.DeleteModel(
            name='SoftwarePurchase',
        ),
    ]
