# Generated by Django 2.0 on 2018-01-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0019_auto_20180104_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('storage_type', models.CharField(max_length=64)),
                ('st_cost_per_gb', models.FloatField()),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='softwarecost',
            name='software_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
