# Generated by Django 2.0 on 2018-01-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0020_auto_20180105_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_log',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='governance_doc',
            name='governance_type',
            field=models.CharField(choices=[('IR', 'IRB'), ('IX', 'IRB Exemption'), ('DU', 'DUA'), ('DC', 'Data Core User Agreement'), ('ON', 'Onboarding Form')], default='DC', max_length=2),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=32),
        ),
    ]
