# Generated by Django 2.0 on 2018-01-08 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0021_auto_20180107_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_log',
            name='applied_to_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Server'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='applied_to_prj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Project'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='applied_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.DC_User'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
