# Generated by Django 2.0 on 2018-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0022_auto_20180107_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='direct_attach_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='vm_size',
            field=models.CharField(choices=[('SM', 'Small (2 CPU, 8GB RAM)'), ('MD', 'Medium (4 CPU, 16GB RAM)'), ('LG', 'Large (8 CPU, 32GB RAM)'), ('XL', 'Extra Large (16 CPU, 64GB RAM)')], default='SM', max_length=2),
        ),
    ]
