# Generated by Django 2.0 on 2018-01-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0023_auto_20180108_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backup_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_host', to='dc_management.Server'),
        ),
        migrations.AddField(
            model_name='project',
            name='db_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='direct_attach_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fileshare_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='host_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='software_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
