# Generated by Django 2.0 on 2018-01-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0024_auto_20180108_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backup_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
