# Generated by Django 2.0 on 2018-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0026_project_project_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requested_cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='requested_ram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
