# Generated by Django 2.0 on 2018-01-20 05:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0029_storage_log_storage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('ticket_description', models.TextField(verbose_name='Description for tickets')),
                ('dc_description', models.TextField(verbose_name='Description for Data Core')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='01/20/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='01/20/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_storage',
            field=models.IntegerField(verbose_name='System storage'),
        ),
        migrations.AlterField(
            model_name='server',
            name='other_storage',
            field=models.IntegerField(verbose_name='Direct attach storage'),
        ),
        migrations.AlterField(
            model_name='storage_log',
            name='date_changed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
