# Generated by Django 2.0 on 2018-02-08 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0033_auto_20180206_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('change_date', models.DateField(default=datetime.date.today)),
                ('ticket', models.CharField(blank=True, max_length=32, null=True)),
                ('external_source', models.CharField(blank=True, max_length=128, null=True)),
                ('external_destination', models.CharField(blank=True, max_length=128, null=True)),
                ('filenames', models.TextField(verbose_name='files for transfer')),
                ('data_type', models.CharField(choices=[('DE', 'Deidentified'), ('ID', 'PHI'), ('LM', 'Limited Dataset'), ('ND', 'Not determined')], default='ND', max_length=2)),
                ('comment', models.TextField()),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_project', to='dc_management.Project')),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.DC_User')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_reviewer', to='dc_management.DC_Administrator')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_project', to='dc_management.Project')),
            ],
            options={
                'verbose_name': 'File Transfer Log',
                'verbose_name_plural': 'File Transfer Logs',
            },
        ),
        migrations.CreateModel(
            name='TransferMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_method', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='02/08/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='02/08/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='transfer_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.TransferMethod'),
        ),
    ]
