# Generated by Django 2.0 on 2018-02-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0034_auto_20180208_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='file_num',
            field=models.IntegerField(default=0, verbose_name='number of files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
