# Generated by Django 2.0 on 2018-02-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0035_auto_20180208_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='02/09/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='02/09/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
