# Generated by Django 2.0 on 2018-02-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0036_auto_20180209_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='02/15/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='02/15/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='postdata_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date data load confirmed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='postdata_ticket',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ticket confirming data loaded'),
        ),
    ]
