# Generated by Django 2.0 on 2018-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0037_auto_20180215_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='operating_sys',
            field=models.CharField(choices=[('M8', 'Microsoft Windows Server 2008 (64-bit)'), ('M2', 'Microsoft Windows Server 2012 (64-bit)'), ('M6', 'Microsoft Windows Server 2016 (64-bit)'), ('R7', 'Red Hat Enterprise Linux 7 (64-bit)'), ('W7', 'Microsoft Windows 7 (64-bit)')], default='M2', max_length=2),
        ),
    ]
