# Generated by Django 2.0 on 2018-02-28 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0038_auto_20180215_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('sn_ticket', models.CharField(blank=True, max_length=32, null=True)),
                ('date_changed', models.DateField(default=datetime.date.today)),
                ('new_RAM', models.IntegerField(blank=True, null=True)),
                ('new_CPU', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Computing Resource Log',
                'verbose_name_plural': 'Computing Resource Logs',
            },
        ),
        migrations.AddField(
            model_name='dc_user',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Primary email address'),
        ),
        migrations.AddField(
            model_name='governance_doc',
            name='destroy_data',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_admin', to='dc_management.DC_User'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='02/28/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='02/28/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='resourcelog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.Project'),
        ),
        migrations.AddField(
            model_name='resourcelog',
            name='record_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dc_user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.Department'),
        ),
    ]
