# Generated by Django 2.0 on 2018-03-03 03:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0040_auto_20180301_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('access_ticket', models.CharField(blank=True, max_length=32, null=True, verbose_name='user access confirmation ticket')),
                ('access_date', models.DateField(default=datetime.date.today, verbose_name='access confirmation date')),
                ('envt_ticket', models.CharField(blank=True, max_length=32, null=True, verbose_name='environment confirmation ticket')),
                ('envt_date', models.DateField(default=datetime.date.today, verbose_name='environment confirmation date')),
                ('data_ticket', models.CharField(blank=True, max_length=32, null=True, verbose_name='data integrity confirmation ticket')),
                ('data_date', models.DateField(default=datetime.date.today, verbose_name='data integrity confirmation date')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Storage Log',
                'verbose_name_plural': 'Storage Logs',
            },
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='03/02/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='03/02/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ON', 'Onboarding'), ('RU', 'Running'), ('CO', 'Completed'), ('SU', 'Suspended'), ('SD', 'Shutting down')], default='RU', max_length=2),
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.Project'),
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='record_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
