# Generated by Django 2.0 on 2018-08-15 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0043_auto_20180305_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('comment', models.TextField()),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_management.CommentLog')),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_admin',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_dcuser',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_govdoc',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_prj',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_server',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_software',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='affected_softwarelicensetype',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alerttag',
            name='type',
        ),
        migrations.AddField(
            model_name='alerttag',
            name='alertcomment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerttag',
            name='cleared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dc_user',
            name='role',
            field=models.CharField(choices=[('FC', 'Faculty'), ('SN', 'Statistician'), ('AF', 'Affiliate'), ('RC', 'Research Coordinator'), ('SF', 'Staff'), ('ST', 'Student'), ('VO', 'Volunteer'), ('DC', 'Data Core Staff'), ('OT', 'Other'), ('EX', 'Role Expired')], default='FC', max_length=2),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='08/15/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='08/15/2018', max_length=32, verbose_name='Start Date'),
        ),
    ]
