# Generated by Django 2.0 on 2018-08-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0044_auto_20180815_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_user',
            name='dynamic_comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to='dc_management.CommentLog'),
        ),
        migrations.AddField(
            model_name='governance_doc',
            name='dynamic_comments',
            field=models.ManyToManyField(blank=True, related_name='govdoc_comments', to='dc_management.CommentLog'),
        ),
        migrations.AddField(
            model_name='project',
            name='dynamic_comments',
            field=models.ManyToManyField(blank=True, related_name='project_comments', to='dc_management.CommentLog'),
        ),
        migrations.AddField(
            model_name='server',
            name='dynamic_comments',
            field=models.ManyToManyField(blank=True, related_name='server_comments', to='dc_management.CommentLog'),
        ),
        migrations.AddField(
            model_name='software',
            name='dynamic_comments',
            field=models.ManyToManyField(blank=True, related_name='software_comments', to='dc_management.CommentLog'),
        ),
    ]
