# Generated by Django 2.0 on 2018-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0045_auto_20180815_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='governance_doc',
            name='isolate_data',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='project',
            name='isolate_data',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='project',
            name='open_allowed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='project',
            name='open_enabled',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='09/14/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='09/14/2018', max_length=32, verbose_name='Start Date'),
        ),
    ]
