# Generated by Django 2.0 on 2018-11-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0048_auto_20181120_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='file_num_unknown',
            field=models.NullBooleanField(verbose_name='file number unknown'),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='filepath_dest',
            field=models.TextField(default=1, verbose_name='destination paths of files for transfer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='11/21/2019', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='11/21/2018', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_project', to='dc_management.Project', verbose_name='Destination project'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='file_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of files'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='filenames',
            field=models.TextField(verbose_name='source paths of files for transfer'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_project', to='dc_management.Project', verbose_name='Source project'),
        ),
    ]
