# Generated by Django 2.1.4 on 2019-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0049_auto_20181121_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='firewalled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='01/03/2020', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='01/03/2019', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='server',
            name='operating_sys',
            field=models.CharField(choices=[('M8', 'Microsoft Windows Server 2008 (64-bit)'), ('M2', 'Microsoft Windows Server 2012 (64-bit)'), ('M6', 'Microsoft Windows Server 2016 (64-bit)'), ('R7', 'Red Hat Enterprise Linux 7 (64-bit)'), ('W7', 'Microsoft Windows 7 (64-bit)'), ('U6', 'Ubuntu 16 LTS (64-bit)')], default='M2', max_length=2),
        ),
    ]
