# Generated by Django 2.1.4 on 2019-04-23 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0052_auto_20190118_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('setup_cost', models.FloatField(blank=True, null=True)),
                ('db_cost', models.FloatField()),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraResourceCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('extra_cpu', models.IntegerField()),
                ('cpu_cost', models.FloatField()),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('billing_date', models.DateField()),
                ('base_expense', models.FloatField(blank=True, null=True)),
                ('storage_expense', models.FloatField(blank=True, null=True)),
                ('sw_expense', models.FloatField(blank=True, null=True)),
                ('hosting_expense', models.FloatField(blank=True, null=True)),
                ('db_expense', models.FloatField(blank=True, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='billing_comments', to='dc_management.CommentLog')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='postdata_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='postdata_ticket',
        ),
        migrations.RemoveField(
            model_name='project',
            name='predata_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='predata_ticket',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='04/22/2020', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='04/23/2019', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='projectbillingrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.Project'),
        ),
        migrations.AddField(
            model_name='projectbillingrecord',
            name='record_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
