# Generated by Django 2.1.4 on 2019-04-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0054_auto_20190423_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='db_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='04/25/2020', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='04/26/2019', max_length=32, verbose_name='Start Date'),
        ),
    ]
