# Generated by Django 2.1.4 on 2019-06-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0055_auto_20190426_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='06/17/2020', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='06/18/2019', max_length=32, verbose_name='Start Date'),
        ),
    ]
