# Generated by Django 2.1.4 on 2019-07-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0057_auto_20190709_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='07/17/2020', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='07/18/2019', max_length=32, verbose_name='Start Date'),
        ),
    ]
