# Generated by Django 2.1.4 on 2019-07-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0058_auto_20190718_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbillingrecord',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='billing_comments', to='dc_management.CommentLog'),
        ),
    ]
