# Generated by Django 2.1.4 on 2019-10-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0059_auto_20190718_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dynamic_comments',
        ),
        migrations.AlterField(
            model_name='access_log',
            name='dc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='audit_log',
            name='dc_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='10/21/2020', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='10/22/2019', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='external_access_log',
            name='user_requesting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='governance_doc',
            name='users_permitted',
            field=models.ManyToManyField(blank=True, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pi', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_admin', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='applied_to_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dc_management.Server'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='applied_to_prj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dc_management.Project'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='applied_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='software_log',
            name='software_changed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dc_management.Software'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
