# Generated by Django 2.1.4 on 2019-10-23 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0019_auto_20191022_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0060_auto_20191022_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(choices=[('IS', 'Isilon'), ('AW', 'Amazon Web Services'), ('AZ', 'Microsoft Azure')], default='IS', max_length=2, verbose_name='Storage location')),
                ('datasets', models.ManyToManyField(to='datacatalog.Dataset')),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='transfer_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dc_management.TransferMethod'),
        ),
        migrations.AddField(
            model_name='project',
            name='storage',
            field=models.ManyToManyField(to='dc_management.Storage'),
        ),
    ]
