# Generated by Django 2.1.4 on 2020-06-11 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0063_auto_20200310_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualProjectAttestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('attestation_date', models.DateField()),
                ('allowed_users', models.ManyToManyField(to='persons.Person')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestation_pi', to='persons.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dc_management.Project')),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataCoreUserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('locations_allowed', models.TextField()),
                ('consent_access', models.CharField(max_length=8, null=True)),
                ('consent_usage', models.CharField(max_length=8, null=True)),
                ('signature_date', models.DateField(null=True)),
                ('signature_name', models.CharField(max_length=64, null=True)),
                ('signature_title', models.CharField(max_length=64, null=True)),
                ('acknowledge_patching', models.CharField(max_length=8, null=True)),
                ('attestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dc_management.Project')),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='06/10/2021', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='06/10/2020', max_length=32, verbose_name='Start Date'),
        ),
    ]
