# Generated by Django 2.1.4 on 2020-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0064_auto_20200610_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbillingrecord',
            name='account',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='06/17/2021', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='06/17/2020', max_length=32, verbose_name='Start Date'),
        ),
    ]
