# Generated by Django 2.1.4 on 2020-06-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0065_auto_20200617_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fileshare_derivative',
            field=models.IntegerField(blank=True, null=True, verbose_name='Derivative data (GB)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='backup_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Archival storage (GB)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fileshare_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Primary data (GB)'),
        ),
    ]
