# Generated by Django 2.1.4 on 2020-11-05 19:03

import cidrfield.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dc_management', '0066_auto_20200617_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('internal_connection', models.NullBooleanField()),
                ('whitelisted', cidrfield.models.IPNetworkField(null=True)),
                ('pusher', models.CharField(blank=True, max_length=128, null=True, verbose_name='External data location')),
                ('pusher_contact', models.CharField(blank=True, max_length=128, null=True, verbose_name='External contact name')),
                ('pusher_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='External contact email')),
                ('login_details', models.EmailField(blank=True, max_length=254, null=True, verbose_name='External connection details')),
                ('firewall_label', models.CharField(blank=True, max_length=128, null=True, verbose_name='Firewall label')),
                ('firewall_rule', models.CharField(blank=True, max_length=32, null=True)),
                ('firewall_request', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='11/05/2021', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='11/05/2020', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='server',
            name='function',
            field=models.CharField(choices=[('PR', 'Production'), ('DB', 'Production Database'), ('TE', 'Test'), ('DE', 'Development')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='sftp',
            name='host_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dc_management.Server'),
        ),
        migrations.AddField(
            model_name='sftp',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_management.Project'),
        ),
        migrations.AddField(
            model_name='sftp',
            name='record_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sftp',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dc_management.Storage'),
        ),
    ]
