# Generated by Django 2.1.4 on 2021-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0069_auto_20201106_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_change_log',
            name='storage_change',
            field=models.CharField(blank=True, choices=[('AS', 'Add storage'), ('RS', 'Remove storage')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='05/18/2022', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='05/18/2021', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='server_change_log',
            name='state_change',
            field=models.CharField(blank=True, choices=[('CO', 'Connected'), ('DC', 'Disconnected')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='datacatalog.Dataset'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(choices=[('IS', 'Isilon'), ('AW', 'Amazon Web Services'), ('AZ', 'Microsoft Azure'), ('SA', 'Secure Remote Archive')], default='IS', max_length=2, verbose_name='Storage location'),
        ),
    ]
