# Generated by Django 3.2 on 2021-11-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0035_auto_20211116_2008'),
        ('dc_management', '0071_auto_20210707_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='staging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datacatalog.dataaccess'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='enddate',
            field=models.CharField(default='11/16/2022', max_length=32, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dcuagenerator',
            name='startdate',
            field=models.CharField(default='11/16/2021', max_length=32, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='storage',
            field=models.ManyToManyField(blank=True, related_name='dc_project', to='datacatalog.DataAccess'),
        ),
        migrations.AlterField(
            model_name='sftp',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datacatalog.dataaccess'),
        ),
    ]
